### ISSUE TITLE
Not all tasks syncing to Google Calendar

### ISSUE THREAD

**Issue by rcowell14** [JHWelch/ChoreManager#38]
Some tasks, specifically "Amy litter" and "Do the dishes" aren't syncing to my Google Calendar after setting up the sync.  I can see Laundry and Budget, but not those or the "Dust" event

## To Reproduce
Go to my Google Calendar, look at date that should have "Do the dishes," and it doesn't show up

## Expected behavior
"do the dishes" should be visible for yesterday

## Actual Behavior
It's not.

## Desktop (please complete the following information):
 - OS: MacOS 10.15.7
 - Browser Chrome
 - Version 90

**Comment by JHWelch** [comment]
Think this has to do with the CalendarTokens returning chores that are owned by a user, not Chore **instances** owned by a user.
